backend: bayes
# window used to summarize trajectories (years)
window_years: 2.0

# spline basis for posterior trajectory sampling
df_basis: 5            # effective df cap per window
n_samples: 1000        # posterior draws
tune: 1000             # warmup
grid_freq: 12          # ~monthly resolution over the window
min_points_per_window: 5

# trajectory classification thresholds (on month-by-month slopes)
flat_thr: -1.0         # |slope| < |flat_thr| -> "flat"
decline_thr: -2.0      # slope < decline_thr -> decline
nonlinear_gap: 3.0     # |mean(faster-half) - mean(slower-half)| > gap -> nonlinear
