name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install minimal deps
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install pytest lifelines numpy pandas
      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q
